// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'BasicDetailsModel.freezed.dart';
part 'BasicDetailsModel.g.dart';

@freezed
class BasicDetailsModel with _$BasicDetailsModel {
  const factory BasicDetailsModel({
    required String profileImage,
    required String name,
    required String birthday,
    required String occupation,
    required String address,
    required String gender,
    required String age,
    required String skinType,
    required String height,
  }) = _BasicDetailsModel;

  /// JSON serialization
  factory BasicDetailsModel.fromJson(Map<String, dynamic> json) =>
      _$BasicDetailsModelFromJson(json);
}
