// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlmdwX7pOVyZGk5UpEBeDkkmP0Hqf4-Ek',
    appId: '1:440626653146:web:36954830adc193c0a5c2e3',
    messagingSenderId: '440626653146',
    projectId: 'datingapp-e1475',
    authDomain: 'datingapp-e1475.firebaseapp.com',
    storageBucket: 'datingapp-e1475.firebasestorage.app',
    measurementId: 'G-0ZEY1GJ0Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7_TBcJL6AFWkUo_dxs-oX-ELJvJD2plw',
    appId: '1:440626653146:android:4f18c3f7456df6e8a5c2e3',
    messagingSenderId: '440626653146',
    projectId: 'datingapp-e1475',
    storageBucket: 'datingapp-e1475.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_0eupvfZULPQfgho5es901Jbg4_Vp4c',
    appId: '1:440626653146:ios:3a8db113aef52a08a5c2e3',
    messagingSenderId: '440626653146',
    projectId: 'datingapp-e1475',
    storageBucket: 'datingapp-e1475.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );
}
